receivers:
  opencensus:
  zipkin:
    endpoint: :9411
  jaeger:
    protocols:
      thrift_http:


exporters:
  awsxray:
    region: us-east-1

  logging:
    loglevel: debug

#  opencensus:
#    endpoint: "otel-collector:55678"
#    insecure: true

processors:
  batch:
  queued_retry:

extensions:
  pprof:
    endpoint: :1777
  zpages:
    endpoint: :55679
  health_check:

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [opencensus, jaeger, zipkin]
      processors: [batch, queued_retry]
#      exporters: [opencensus, logging, awsxray]
      exporters: [awsxray]
    metrics:
      receivers: [opencensus]
      processors: [batch]
      exporters: [logging]
#      exporters: [logging,opencensus]
